# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0901.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.Requests = QtWidgets.QWidget()
        self.Requests.setObjectName("Requests")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Requests)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FilenameTxtRequest = QtWidgets.QLineEdit(self.Requests)
        self.FilenameTxtRequest.setEnabled(True)
        self.FilenameTxtRequest.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtRequest.setObjectName("FilenameTxtRequest")
        self.horizontalLayout_8.addWidget(self.FilenameTxtRequest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.FilenameTxtRequest1 = QtWidgets.QLineEdit(self.Requests)
        self.FilenameTxtRequest1.setEnabled(True)
        self.FilenameTxtRequest1.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtRequest1.setObjectName("FilenameTxtRequest1")
        self.horizontalLayout_9.addWidget(self.FilenameTxtRequest1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LineEditRequest = QtWidgets.QLineEdit(self.Requests)
        self.LineEditRequest.setMinimumSize(QtCore.QSize(0, 30))
        self.LineEditRequest.setText("")
        self.LineEditRequest.setObjectName("LineEditRequest")
        self.horizontalLayout_5.addWidget(self.LineEditRequest)
        self.ResultRequest = QtWidgets.QPushButton(self.Requests)
        self.ResultRequest.setMinimumSize(QtCore.QSize(80, 30))
        self.ResultRequest.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ResultRequest.setObjectName("ResultRequest")
        self.horizontalLayout_5.addWidget(self.ResultRequest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.TextResult = QtWidgets.QTextBrowser(self.Requests)
        self.TextResult.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TextResult.setFont(font)
        self.TextResult.setObjectName("TextResult")
        self.verticalLayout_3.addWidget(self.TextResult)
        self.CheckResultRequest = QtWidgets.QCheckBox(self.Requests)
        self.CheckResultRequest.setEnabled(False)
        self.CheckResultRequest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CheckResultRequest.setObjectName("CheckResultRequest")
        self.verticalLayout_3.addWidget(self.CheckResultRequest)
        self.CheckFailRequest = QtWidgets.QCheckBox(self.Requests)
        self.CheckFailRequest.setEnabled(False)
        self.CheckFailRequest.setObjectName("CheckFailRequest")
        self.verticalLayout_3.addWidget(self.CheckFailRequest)
        self.Button = QtWidgets.QToolButton(self.Requests)
        self.Button.setObjectName("Button")
        self.verticalLayout_3.addWidget(self.Button)
        self.TabWidget.addTab(self.Requests, "")
        self.horizontalLayout.addWidget(self.TabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Самое Лучшее Приложение"))
        self.LineEditRequest.setPlaceholderText(_translate("MainWindow", "Введите запрос..."))
        self.ResultRequest.setText(_translate("MainWindow", "Выполнить"))
        self.TextResult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12.25pt;\"><br /></p></body></html>"))
        self.CheckResultRequest.setText(_translate("MainWindow", "Программа завершила работу"))
        self.CheckFailRequest.setText(_translate("MainWindow", "Упал с ошибкой"))
        self.Button.setText(_translate("MainWindow", "..."))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Requests), _translate("MainWindow", "Запросы"))
