from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 700)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.Requests = QtWidgets.QWidget()
        self.Requests.setObjectName("Requests")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Requests)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FilenameTxtRequest = QtWidgets.QLineEdit(self.Requests)
        self.FilenameTxtRequest.setEnabled(False)
        self.FilenameTxtRequest.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtRequest.setObjectName("FilenameTxtRequest")
        self.horizontalLayout_8.addWidget(self.FilenameTxtRequest)
        self.BrowserTxtRequest = QtWidgets.QPushButton(self.Requests)
        self.BrowserTxtRequest.setMinimumSize(QtCore.QSize(120, 30))
        self.BrowserTxtRequest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BrowserTxtRequest.setFont(font)
        self.BrowserTxtRequest.setObjectName("BrowserTxtRequest")
        self.horizontalLayout_8.addWidget(self.BrowserTxtRequest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.FilenameTxtRequest1 = QtWidgets.QLineEdit(self.Requests)
        self.FilenameTxtRequest1.setEnabled(False)
        self.FilenameTxtRequest1.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtRequest1.setObjectName("FilenameTxtRequest1")
        self.horizontalLayout_9.addWidget(self.FilenameTxtRequest1)
        self.BrowserTxtRequest1 = QtWidgets.QPushButton(self.Requests)
        self.BrowserTxtRequest1.setMinimumSize(QtCore.QSize(120, 30))
        self.BrowserTxtRequest1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BrowserTxtRequest1.setObjectName("BrowserTxtRequest1")
        self.horizontalLayout_9.addWidget(self.BrowserTxtRequest1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LineEditRequest = QtWidgets.QLineEdit(self.Requests)
        self.LineEditRequest.setMinimumSize(QtCore.QSize(0, 30))
        self.LineEditRequest.setText("")
        self.LineEditRequest.setObjectName("LineEditRequest")
        self.horizontalLayout_5.addWidget(self.LineEditRequest)
        self.ResultRequest = QtWidgets.QPushButton(self.Requests)
        self.ResultRequest.setMinimumSize(QtCore.QSize(80, 30))
        self.ResultRequest.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ResultRequest.setObjectName("ResultRequest")
        self.horizontalLayout_5.addWidget(self.ResultRequest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.TextResult = QtWidgets.QTextBrowser(self.Requests)
        self.TextResult.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TextResult.setFont(font)
        self.TextResult.setObjectName("TextResult")
        self.verticalLayout_3.addWidget(self.TextResult)
        self.CheckResultRequest = QtWidgets.QCheckBox(self.Requests)
        self.CheckResultRequest.setEnabled(False)
        self.CheckResultRequest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CheckResultRequest.setObjectName("CheckResultRequest")
        self.verticalLayout_3.addWidget(self.CheckResultRequest)
        self.CheckFailRequest = QtWidgets.QCheckBox(self.Requests)
        self.CheckFailRequest.setEnabled(False)
        self.CheckFailRequest.setObjectName("CheckFailRequest")
        self.verticalLayout_3.addWidget(self.CheckFailRequest)
        self.Button = QtWidgets.QToolButton(self.Requests)
        self.Button.setObjectName("Button")
        self.verticalLayout_3.addWidget(self.Button)
        self.TabWidget.addTab(self.Requests, "")
        self.Origins = QtWidgets.QWidget()
        self.Origins.setObjectName("Origins")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Origins)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FilenameJsonOrigin = QtWidgets.QLineEdit(self.Origins)
        self.FilenameJsonOrigin.setEnabled(False)
        self.FilenameJsonOrigin.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameJsonOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FilenameJsonOrigin.setMouseTracking(False)
        self.FilenameJsonOrigin.setFrame(True)
        self.FilenameJsonOrigin.setObjectName("FilenameJsonOrigin")
        self.horizontalLayout_4.addWidget(self.FilenameJsonOrigin)
        self.BrowserJsonOrigin = QtWidgets.QPushButton(self.Origins)
        self.BrowserJsonOrigin.setMinimumSize(QtCore.QSize(120, 30))
        self.BrowserJsonOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BrowserJsonOrigin.setObjectName("BrowserJsonOrigin")
        self.horizontalLayout_4.addWidget(self.BrowserJsonOrigin)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FilenameTxtOrigin = QtWidgets.QLineEdit(self.Origins)
        self.FilenameTxtOrigin.setEnabled(False)
        self.FilenameTxtOrigin.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtOrigin.setObjectName("FilenameTxtOrigin")
        self.horizontalLayout_2.addWidget(self.FilenameTxtOrigin)
        self.BrowserTxtOrigin = QtWidgets.QPushButton(self.Origins)
        self.BrowserTxtOrigin.setMinimumSize(QtCore.QSize(120, 30))
        self.BrowserTxtOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BrowserTxtOrigin.setObjectName("BrowserTxtOrigin")
        self.horizontalLayout_2.addWidget(self.BrowserTxtOrigin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NewNameOrigin = QtWidgets.QLineEdit(self.Origins)
        self.NewNameOrigin.setMinimumSize(QtCore.QSize(0, 30))
        self.NewNameOrigin.setText("")
        self.NewNameOrigin.setObjectName("NewNameOrigin")
        self.horizontalLayout_3.addWidget(self.NewNameOrigin)
        self.ResultOrigin = QtWidgets.QPushButton(self.Origins)
        self.ResultOrigin.setMinimumSize(QtCore.QSize(0, 30))
        self.ResultOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ResultOrigin.setCheckable(False)
        self.ResultOrigin.setObjectName("ResultOrigin")
        self.horizontalLayout_3.addWidget(self.ResultOrigin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.CheckResultOrigin = QtWidgets.QCheckBox(self.Origins)
        self.CheckResultOrigin.setEnabled(False)
        self.CheckResultOrigin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CheckResultOrigin.setObjectName("CheckResultOrigin")
        self.verticalLayout.addWidget(self.CheckResultOrigin)
        self.CheckFailOrigin = QtWidgets.QCheckBox(self.Origins)
        self.CheckFailOrigin.setEnabled(False)
        self.CheckFailOrigin.setObjectName("CheckFailOrigin")
        self.verticalLayout.addWidget(self.CheckFailOrigin)
        self.TabWidget.addTab(self.Origins, "")
        self.Exons = QtWidgets.QWidget()
        self.Exons.setObjectName("Exons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Exons)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FilenameTxtExon = QtWidgets.QLineEdit(self.Exons)
        self.FilenameTxtExon.setEnabled(False)
        self.FilenameTxtExon.setMinimumSize(QtCore.QSize(120, 30))
        self.FilenameTxtExon.setObjectName("FilenameTxtExon")
        self.horizontalLayout_6.addWidget(self.FilenameTxtExon)
        self.BrowserTxtExon = QtWidgets.QPushButton(self.Exons)
        self.BrowserTxtExon.setMinimumSize(QtCore.QSize(120, 30))
        self.BrowserTxtExon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BrowserTxtExon.setObjectName("BrowserTxtExon")
        self.horizontalLayout_6.addWidget(self.BrowserTxtExon)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NewNameExon = QtWidgets.QLineEdit(self.Exons)
        self.NewNameExon.setMinimumSize(QtCore.QSize(0, 30))
        self.NewNameExon.setText("")
        self.NewNameExon.setObjectName("NewNameExon")
        self.verticalLayout_4.addWidget(self.NewNameExon)
        self.CountExon = QtWidgets.QLineEdit(self.Exons)
        self.CountExon.setMinimumSize(QtCore.QSize(0, 30))
        self.CountExon.setText("")
        self.CountExon.setObjectName("CountExon")
        self.verticalLayout_4.addWidget(self.CountExon)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.ResultExon = QtWidgets.QPushButton(self.Exons)
        self.ResultExon.setMinimumSize(QtCore.QSize(80, 30))
        self.ResultExon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ResultExon.setCheckable(False)
        self.ResultExon.setObjectName("ResultExon")
        self.horizontalLayout_7.addWidget(self.ResultExon)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.CheckResultExon = QtWidgets.QCheckBox(self.Exons)
        self.CheckResultExon.setEnabled(False)
        self.CheckResultExon.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CheckResultExon.setObjectName("CheckResultExon")
        self.verticalLayout_2.addWidget(self.CheckResultExon)
        self.CheckFailExon = QtWidgets.QCheckBox(self.Exons)
        self.CheckFailExon.setEnabled(False)
        self.CheckFailExon.setObjectName("CheckFailExon")
        self.verticalLayout_2.addWidget(self.CheckFailExon)
        self.TabWidget.addTab(self.Exons, "")
        self.horizontalLayout.addWidget(self.TabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Самое Лучшее Приложение"))
        self.BrowserTxtRequest.setText(_translate("MainWindow", "Выбрать Оригинал"))
        self.BrowserTxtRequest1.setText(_translate("MainWindow", "Выбрать txt-файл"))
        self.LineEditRequest.setPlaceholderText(_translate("MainWindow", "Введите запрос..."))
        self.ResultRequest.setText(_translate("MainWindow", "Выполнить"))
        self.TextResult.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12.25pt;\"><br /></p></body></html>"))
        self.CheckResultRequest.setText(_translate("MainWindow", "Программа завершила работу"))
        self.CheckFailRequest.setText(_translate("MainWindow", "Упал с ошибкой"))
        self.Button.setText(_translate("MainWindow", "..."))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Requests), _translate("MainWindow", "Запросы"))
        self.BrowserJsonOrigin.setText(_translate("MainWindow", "Выбрать json-файл"))
        self.BrowserTxtOrigin.setText(_translate("MainWindow", "Выбрать txt-файл"))
        self.NewNameOrigin.setPlaceholderText(_translate("MainWindow", "Введите название для новго файла..."))
        self.ResultOrigin.setText(_translate("MainWindow", "Выполнить"))
        self.CheckResultOrigin.setText(_translate("MainWindow", "Программа завершила работу"))
        self.CheckFailOrigin.setText(_translate("MainWindow", "Упал с ошибкой"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Origins), _translate("MainWindow", "Создание Оригинальной"))
        self.BrowserTxtExon.setText(_translate("MainWindow", "Выбрать txt-файл"))
        self.NewNameExon.setPlaceholderText(_translate("MainWindow", "Введите название для новго файла..."))
        self.CountExon.setPlaceholderText(_translate("MainWindow", "Введите количество лишних символов в начале..."))
        self.ResultExon.setText(_translate("MainWindow", "Выполнить"))
        self.CheckResultExon.setText(_translate("MainWindow", "Программа завершила работу"))
        self.CheckFailExon.setText(_translate("MainWindow", "Упал с ошибкой"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Exons), _translate("MainWindow", "Создание txt"))
